chore: try to cache IDEA indexes to speed up CI (#66)

diff --git a/.github/workflows/quality-check.yaml b/.github/workflows/quality-check.yaml
--- a/.github/workflows/quality-check.yaml
+++ b/.github/workflows/quality-check.yaml
@@ -82,7 +82,12 @@ jobs:
         with:
           distribution: 'adopt'
           java-version: '17'
-          cache: 'gradle'
+      - name: Setup Gradle
+        uses: gradle/actions/setup-gradle@v4
+        with:
+            dependency-graph: 'generate-and-submit'
+            dependency-graph-continue-on-failure: false
+            gradle-home-cache-cleanup: true
       - name: Run Dependency Updates
         run: |
           ./gradlew --quiet --console=plain dependencyUpdates
@@ -98,7 +103,10 @@ jobs:
         with:
           distribution: 'adopt'
           java-version: '17'
-          cache: 'gradle'
+      - name: Setup Gradle
+        uses: gradle/actions/setup-gradle@v4
+        with:
+            gradle-home-cache-cleanup: true
       - name: Run Linter
         run: |
           ./gradlew --quiet --console=plain ktlintCheck
@@ -119,7 +127,10 @@ jobs:
         with:
           distribution: 'adopt'
           java-version: '17'
-          cache: 'gradle'
+      - name: Setup Gradle
+        uses: gradle/actions/setup-gradle@v4
+        with:
+            gradle-home-cache-cleanup: true
       - name: Setup Docker (for Test Containers)
         run: |
           sudo apt update -y
@@ -160,7 +171,17 @@ jobs:
         with:
           distribution: 'zulu'
           java-version: '17'
-          cache: 'gradle'
+      - name: Setup Gradle
+        uses: gradle/actions/setup-gradle@v4
+        with:
+            gradle-home-cache-cleanup: true
+      - name: Restore IDEA Cached Indexes
+        uses: actions/cache/restore@v4
+        with:
+          key: 'intellij-indexes-cache'
+          path: |
+            packages/jetbrains-plugin/build/idea-sandbox/system-test/index
+            packages/jetbrains-plugin/build/idea-sandbox/system/index
       - name: Prepare License Key
         env:
           JB_TEST_KEY: ${{ secrets.JB_TEST_KEY }}
@@ -193,7 +214,17 @@ jobs:
             **/build/reports/**/*.html
             **/build/reports/**/*.log
             **/build/reports/*/*.png
+            **/build/idea-sandbox/system/**/*.log
+            **/build/idea-sandbox/system-test/**/*.log
             **/video/**/*.avi
+      - name: Cache IDEA Indexes
+        uses: actions/cache/save@v4
+        if: success() || failure() # always run even if the previous step fails
+        with:
+          key: 'intellij-indexes-cache'
+          path: |
+              packages/jetbrains-plugin/build/idea-sandbox/system-test/index
+              packages/jetbrains-plugin/build/idea-sandbox/system/index
       - name: Publish Test Report
         uses: mikepenz/action-junit-report@v4
         if: success() || failure() # always run even if the previous step fails
@@ -213,7 +244,10 @@ jobs:
         with:
           distribution: 'adopt'
           java-version: '17'
-          cache: 'gradle'
+      - name: Setup Gradle
+        uses: gradle/actions/setup-gradle@v4
+        with:
+            gradle-home-cache-cleanup: true
       - name: Performance Tests
         run: |
           ./gradlew --quiet --console=plain ":packages:jetbrains-plugin:jmh"
@@ -240,7 +274,10 @@ jobs:
         with:
           distribution: 'adopt'
           java-version: '17'
-          cache: 'gradle'
+      - name: Setup Gradle
+        uses: gradle/actions/setup-gradle@v4
+        with:
+            gradle-home-cache-cleanup: true
       - name: Verify Plugin
         run: |
           ./gradlew ":packages:jetbrains-plugin:verifyPlugin"
