chore: fix integration with testing framework

diff --git a/.github/workflows/quality-check.yaml b/.github/workflows/quality-check.yaml
--- a/.github/workflows/quality-check.yaml
+++ b/.github/workflows/quality-check.yaml
@@ -26,7 +26,7 @@ jobs:
           cache: 'gradle'
       - name: Run Dependency Updates
         run: |
-          ./gradlew dependencyUpdates
+          ./gradlew --quiet --console=plain dependencyUpdates
 
   style-check:
     name: 'Style Check'
@@ -42,7 +42,7 @@ jobs:
           cache: 'gradle'
       - name: Run Linter
         run: |
-          ./gradlew spotlessApply
+          ./gradlew --quiet --console=plain spotlessApply
 
   unit-tests:
     name: 'Unit Tests'
@@ -58,7 +58,12 @@ jobs:
           cache: 'gradle'
       - name: SBOM Generation
         run: |
-          ./gradlew test
+          ./gradlew --quiet --console=plain test
+      - name: Publish Unit Test Report
+        uses: mikepenz/action-junit-report@v4
+        if: success() || failure() # always run even if the previous step fails
+        with:
+          report_paths: '**/build/test-results/test/TEST-*.xml'
 
   cyclonedx-sbom-generation:
     name: 'SBOM Generation'
@@ -74,7 +79,7 @@ jobs:
           cache: 'gradle'
       - name: SBOM Generation
         run: |
-          ./gradlew ":packages:jetbrains-plugin:cyclonedxBom"
+          ./gradlew --quiet --console=plain ":packages:jetbrains-plugin:cyclonedxBom"
     
   functional-tests:
     name: 'Functional & UI Tests'
@@ -95,7 +100,12 @@ jobs:
           cache: 'gradle'
       - name: Functional Tests
         run: |
-          ./gradlew functionalTests
+          ./gradlew --quiet --console=plain ":packages:jetbrains-plugin:test"
+      - name: Publish Functional Test Report
+        uses: mikepenz/action-junit-report@v4
+        if: success() || failure() # always run even if the previous step fails
+        with:
+          report_paths: '**/build/test-results/test/TEST-*.xml'
 
   test-coverage:
     name: 'Test Coverage'
@@ -134,7 +144,7 @@ jobs:
           cache: 'gradle'
       - name: Performance Tests
         run: |
-          ./gradlew performanceTest
+          ./gradlew --quiet --console=plain ":packages:jetbrains-plugin:jmh"
 
   verify-plugin:
     name: "Verify Plugin"
