chore: show test results even if they fail

diff --git a/.github/workflows/quality-check.yaml b/.github/workflows/quality-check.yaml
--- a/.github/workflows/quality-check.yaml
+++ b/.github/workflows/quality-check.yaml
@@ -59,7 +59,12 @@ jobs:
           cache: 'gradle'
       - name: Run Test Suite
         run: |
-          ./gradlew --quiet --console=plain test
+          ./gradlew --quiet --console=plain "clean" "cleanTest" "test"
+      - name: Publish Test Report
+        uses: mikepenz/action-junit-report@v4
+        if: success() || failure() # always run even if the previous step fails
+        with:
+          report_paths: '**/build/test-results/test/TEST-*.xml'
 
   cyclonedx-sbom-generation:
     name: 'SBOM Generation'
@@ -96,7 +101,7 @@ jobs:
           cache: 'gradle'
       - name: Functional Tests
         run: |
-          ./gradlew --quiet --console=plain ":packages:jetbrains-plugin:test"
+          ./gradlew --quiet --console=plain "clean" ":packages:jetbrains-plugin:cleanTest" ":packages:jetbrains-plugin:test"
       - name: Publish Test Report
         uses: mikepenz/action-junit-report@v4
         if: success() || failure() # always run even if the previous step fails
