chore: disable functional tests (#108)

diff --git a/.github/workflows/quality-check.yaml b/.github/workflows/quality-check.yaml
--- a/.github/workflows/quality-check.yaml
+++ b/.github/workflows/quality-check.yaml
@@ -174,90 +174,90 @@ jobs:
           pass-emoji: "✅"
           fail-emoji: "🚫"
 
-  functional-tests:
-    name: "UI Tests"
-    runs-on: ubuntu-latest
-    needs:
-      - catalog-check
-      - style-check
-      - unit-tests
-    steps:
-      - name: Checkout
-        uses: actions/checkout@v4
-
-      - name: Setup JDK
-        uses: actions/setup-java@v4
-        with:
-          distribution: "temurin"
-          java-version: "17"
-
-      - name: Setup Gradle
-        uses: gradle/actions/setup-gradle@v4
-        with:
-          gradle-home-cache-cleanup: true
-
-      - name: Restore IDEA Cached Indexes
-        uses: actions/cache/restore@v4
-        with:
-          key: "intellij-indexes-cache"
-          path: |
-            packages/jetbrains-plugin/build/idea-sandbox/system-test/index
-            packages/jetbrains-plugin/build/idea-sandbox/system/index
-
-      - name: Prepare License Key
-        env:
-          JB_TEST_KEY: ${{ secrets.JB_TEST_KEY }}
-        run: |
-          mkdir -p packages/jetbrains-plugin/build/idea-sandbox/config-uiTest
-          echo "$JB_TEST_KEY" | base64 -d > packages/jetbrains-plugin/build/idea-sandbox/config-uiTest/idea.key
-
-      - name: Start UI Test Environment
-        run: |
-          export DISPLAY=:99.0
-          Xvfb -ac :99 -screen 0 1920x1080x24 &
-          sleep 10
-          mkdir -p packages/jetbrains-plugin/build/reports
-          ./gradlew :packages:jetbrains-plugin:runIdeForUiTests > packages/jetbrains-plugin/build/reports/idea.log &
-
-      - name: Wait for IDE to start
-        uses: jtalk/url-health-check-action@b716ccb6645355dd9fcce8002ce460e5474f7f00 # v4
-        with:
-          url: "http://127.0.0.1:8082"
-          max-attempts: 15
-          retry-delay: 30s
-
-      - name: Run UI Tests
-        run: |
-          export DISPLAY=:99.0
-          ./gradlew --quiet --console=plain :packages:jetbrains-plugin:uiTest
-
-      - uses: actions/upload-artifact@v4
-        name: Upload UI Test Failures
-        if: success() || failure() # always run even if the previous step fails
-        with:
-          name: ui-test-failures
-          path: |
-            **/build/reports/**/*.html
-            **/build/reports/**/*.log
-            **/build/reports/**/*.png
-            **/build/idea-sandbox/system/**/*.log
-            **/build/idea-sandbox/system-test/**/*.log
-            **/video/**/*.avi
-
-      - name: Cache IDEA Indexes
-        uses: actions/cache/save@v4
-        if: success() || failure() # always run even if the previous step fails
-        with:
-          key: "intellij-indexes-cache"
-          path: |
-            packages/jetbrains-plugin/build/idea-sandbox/system-test/index
-            packages/jetbrains-plugin/build/idea-sandbox/system/index
-
-      - name: Publish Test Report
-        uses: mikepenz/action-junit-report@a427a90771729d8f85b6ab0cdaa1a5929cab985d # 5.0.0
-        if: success() || failure() # always run even if the previous step fails
-        with:
-          report_paths: "**/build/test-results/test/TEST-*.xml"
+#  functional-tests:
+#    name: "UI Tests"
+#    runs-on: ubuntu-latest
+#    needs:
+#      - catalog-check
+#      - style-check
+#      - unit-tests
+#    steps:
+#      - name: Checkout
+#        uses: actions/checkout@v4
+#
+#      - name: Setup JDK
+#        uses: actions/setup-java@v4
+#        with:
+#          distribution: "temurin"
+#          java-version: "17"
+#
+#      - name: Setup Gradle
+#        uses: gradle/actions/setup-gradle@v4
+#        with:
+#          gradle-home-cache-cleanup: true
+#
+#      - name: Restore IDEA Cached Indexes
+#        uses: actions/cache/restore@v4
+#        with:
+#          key: "intellij-indexes-cache"
+#          path: |
+#            packages/jetbrains-plugin/build/idea-sandbox/system-test/index
+#            packages/jetbrains-plugin/build/idea-sandbox/system/index
+#
+#      - name: Prepare License Key
+#        env:
+#          JB_TEST_KEY: ${{ secrets.JB_TEST_KEY }}
+#        run: |
+#          mkdir -p packages/jetbrains-plugin/build/idea-sandbox/config-uiTest
+#          echo "$JB_TEST_KEY" | base64 -d > packages/jetbrains-plugin/build/idea-sandbox/config-uiTest/idea.key
+#
+#      - name: Start UI Test Environment
+#        run: |
+#          export DISPLAY=:99.0
+#          Xvfb -ac :99 -screen 0 1920x1080x24 &
+#          sleep 10
+#          mkdir -p packages/jetbrains-plugin/build/reports
+#          ./gradlew :packages:jetbrains-plugin:runIdeForUiTests > packages/jetbrains-plugin/build/reports/idea.log &
+#
+#      - name: Wait for IDE to start
+#        uses: jtalk/url-health-check-action@b716ccb6645355dd9fcce8002ce460e5474f7f00 # v4
+#        with:
+#          url: "http://127.0.0.1:8082"
+#          max-attempts: 15
+#          retry-delay: 30s
+#
+#      - name: Run UI Tests
+#        run: |
+#          export DISPLAY=:99.0
+#          ./gradlew --quiet --console=plain :packages:jetbrains-plugin:uiTest
+#
+#      - uses: actions/upload-artifact@v4
+#        name: Upload UI Test Failures
+#        if: success() || failure() # always run even if the previous step fails
+#        with:
+#          name: ui-test-failures
+#          path: |
+#            **/build/reports/**/*.html
+#            **/build/reports/**/*.log
+#            **/build/reports/**/*.png
+#            **/build/idea-sandbox/system/**/*.log
+#            **/build/idea-sandbox/system-test/**/*.log
+#            **/video/**/*.avi
+#
+#      - name: Cache IDEA Indexes
+#        uses: actions/cache/save@v4
+#        if: success() || failure() # always run even if the previous step fails
+#        with:
+#          key: "intellij-indexes-cache"
+#          path: |
+#            packages/jetbrains-plugin/build/idea-sandbox/system-test/index
+#            packages/jetbrains-plugin/build/idea-sandbox/system/index
+#
+#      - name: Publish Test Report
+#        uses: mikepenz/action-junit-report@a427a90771729d8f85b6ab0cdaa1a5929cab985d # 5.0.0
+#        if: success() || failure() # always run even if the previous step fails
+#        with:
+#          report_paths: "**/build/test-results/test/TEST-*.xml"
 
   fitness-check:
     name: "Fitness Check"
@@ -297,7 +297,8 @@ jobs:
     runs-on: ubuntu-latest
     needs:
       - fitness-check
-      - functional-tests
+#      Disabling functional tests while we're waiting for JB team to resolve our CI license issue
+#      - functional-tests
     steps:
       - name: Checkout
         uses: actions/checkout@v4
